CREATE TABLE kitchen_tickets (
    id BIGSERIAL PRIMARY KEY,
    ticket_id VARCHAR(255) UNIQUE NOT NULL,
    order_id VARCHAR(255) UNIQUE NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    status VARCHAR(50) NOT NULL
);
